language: node_js
node_js:
  - "9"
install:
  - cd ..
  - mkdir mol
  - git init
  - git remote add origin https://github.com/eigenmethod/mam.git
  - git pull origin master
  - git clone mol https://github.com/eigenmethod/mol.git
  - mv mol_icon mol/icon
  - npm install
script:
  - npm start mol/icon/demo
  - mv mol/icon/demo/- mol_icon
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: .
  on:
    branch: master
